In [61]:
import numpy as np

Q1:

In [70]:

#With array_split method: unequal array data distribution
#create an array
arr = np.array([0, 1, 2, 3, 4])
#split array into 3 parts
a,b,c = np.array_split(arr, 3)
print("Array 1: ", a)
print("Array 2: ", b)
print("Array 3: ", c)

Array 1:  [0 1]
Array 2:  [2 3]
Array 3:  [4]


Q2:

In [71]:
#flip method : for 2D Array
#create a 2d array
flip_arr = np.array([[1,0],[0,2]])
print("Original Array: \n", flip_arr)
#flip items method used
print("After using flip method: \n", np.flip(flip_arr, axis= 1)) #row-wise exchange


Original Array: 
 [[1 0]
 [0 2]]
After using flip method: 
 [[0 1]
 [2 0]]


Q3:

In [73]:
#pad method: 2D array of ones (4*4) with output border of zeros
arr_ones = np.ones((4,4))
print("Original Array: \n", arr_ones)
print("After zeros border padding: \n", np.pad(arr_ones, pad_width = 1, mode = 'constant', constant_values = 0))


Original Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After zeros border padding: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


Q4:

In [66]:
#row-vector can be converted to column-vector only by increasin the dimension of the existing array by one more dimension
#create 1d array
arr_row = np.array([1,2,3])
print(arr_row)
print("Array dimension: ",arr_row.ndim)
#convert into 2d
arr_swapaxes = arr_row[np.newaxis,:] #column-wise
print(arr_swapaxes)
print("Array dimension: ", arr_swapaxes.ndim)
#convert into column vector using swapaxes function
arr_column= np.swapaxes(arr_swapaxes,0,1)
print(arr_column)
print("Array dimension: ",  arr_column.ndim)



[1 2 3]
Array dimension:  1
[[1 2 3]]
Array dimension:  2
[[1]
 [2]
 [3]]
Array dimension:  2
